Modal window with special char
Filiosoft/npm-audit-html pull request #84
Opened 2022-01-26 10:03 UTC by arunVananth

When the module name has special characters ('@' and '/') the link to modal window doesn't work.

Handled the same by removing these characters when creating data-target-model

2022-01-26 15:09 UTC, nprail requested changes
Please run `npm run lint!` on this and then I'll get it merged in. Thanks for the fix!

2022-01-27 18:08 UTC, arunVananth commented
> Please run `npm run lint!` on this and then I'll get it merged in. Thanks for the fix!

Ran "npm run lint!" on "gh pr checkout 84" and no further fix was required on the current code

2022-01-28 14:37 UTC, nprail approved these changes

2022-01-28 14:39 UTC, merged

2022-01-28 14:49 UTC, nprail commented
:tada: This PR is included in version 2.0.0-beta.2 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/npm-audit-html/v/2.0.0-beta.2)
- [GitHub release](https://github.com/eventOneHQ/npm-audit-html/releases/tag/v2.0.0-beta.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: